package exam.shared;

public enum UserOption {
    MAIN_MENU, LIST_STUDENTS, LIST_EXAMS, LIST_STUDENTS_AND_EXAMS_TAKEN, LIST_RESULTS, ADD_STUDENT, ADD_EXAM, ADD_EXAM_TO_STUDENT, INPUT, BACK, QUIT, PRINT,
}
